# Generated by Django 5.2.7 on 2025-11-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
